# Form implementation generated from reading ui file 'program2.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1560)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 10, 651, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 130, 961, 171))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(70, 30, 71, 16))
        self.label_2.setObjectName("label_2")
        self.nhap_so_thap_phan = QtWidgets.QLineEdit(parent=self.groupBox)
        self.nhap_so_thap_phan.setGeometry(QtCore.QRect(160, 30, 771, 21))
        self.nhap_so_thap_phan.setObjectName("nhap_so_thap_phan")
        self.doi = QtWidgets.QPushButton(parent=self.groupBox)
        self.doi.setGeometry(QtCore.QRect(450, 80, 75, 24))
        self.doi.setObjectName("doi")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(70, 120, 71, 16))
        self.label_3.setObjectName("label_3")
        self.hien_so_nhi_phan = QtWidgets.QLineEdit(parent=self.groupBox)
        self.hien_so_nhi_phan.setGeometry(QtCore.QRect(160, 120, 771, 21))
        self.hien_so_nhi_phan.setObjectName("hien_so_nhi_phan")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 340, 961, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(80, 50, 71, 16))
        self.label_4.setObjectName("label_4")
        self.nhap_so_nhi_phan = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.nhap_so_nhi_phan.setGeometry(QtCore.QRect(190, 50, 741, 21))
        self.nhap_so_nhi_phan.setObjectName("nhap_so_nhi_phan")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(80, 140, 71, 16))
        self.label_5.setObjectName("label_5")
        self.doi2 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.doi2.setGeometry(QtCore.QRect(460, 90, 75, 24))
        self.doi2.setObjectName("doi2")
        self.hien_so_thap_phan = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.hien_so_thap_phan.setGeometry(QtCore.QRect(190, 140, 741, 21))
        self.hien_so_thap_phan.setObjectName("hien_so_thap_phan")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.reverse_convert_button = QtWidgets.QPushButton(self.groupBox_2)
        self.reverse_convert_button.setGeometry(QtCore.QRect(460, 90, 75, 24))
        self.reverse_convert_button.setObjectName("reverse_convert_button")
        self.reverse_convert_button.setText("Đổi")
        self.reverse_convert_button.clicked.connect(self.reverse_convert)
    def convert(self):
        decimal_value = int(self.nhap_so_thap_phan.text())
        binary_value = bin(decimal_value)[2:]  # Bỏ qua '0b' ở đầu
        self.hien_so_nhi_phan.setText(binary_value)
    def reverse_convert(self):
        binary_value = self.nhap_so_nhi_phan.text()
        try:
            decimal_value = int(binary_value, 2)
            self.hien_so_thap_phan.setText(str(decimal_value))
        except ValueError:
            self.hien_so_thap_phan.setText("Giá trị không hợp lệ")
    def convert_decimal_to_binary(self):
        decimal_value = int(self.nhap_so_thap_phan.text())
        binary_value = bin(decimal_value)[2:]
        self.hien_so_nhi_phan.setText(binary_value)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ứng dụng đổi số thập phân sang số nhị phân và ngược lại"))
        self.groupBox.setTitle(_translate("MainWindow", "Chuyển đổi số thập phân sang số nhị phân"))
        self.label_2.setText(_translate("MainWindow", "Số thập phân"))
        self.doi.setText(_translate("MainWindow", "Đổi"))
        self.label_3.setText(_translate("MainWindow", "Số nhị phân"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Chuyển đổi số nhị phân sang số nhị phân"))
        self.label_4.setText(_translate("MainWindow", "Số nhị phân"))
        self.label_5.setText(_translate("MainWindow", "Số thập phân"))
        self.doi2.setText(_translate("MainWindow", "Đổi"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.doi.clicked.connect(ui.convert)
    ui.doi2.clicked.connect(ui.reverse_convert)
    ui.doi.clicked.connect(ui.convert_decimal_to_binary)
    MainWindow.show()
    sys.exit(app.exec())
